# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

containerApp:
  image: registry.gitlab.com/pj-devops/django-app:1.0.8

containerDB:
  image: postgres:13-alpine


